using DotMake.CommandLine;

namespace EXDTooler;

[CliCommand(Parent = typeof(MainCommand))]
public sealed class ExportColumnsCommand
{
    public required MainCommand Parent { get; set; }

    [CliOption(Required = false, Description = "Path to the game directory. Should be the root of the game's repository.", ValidationRules = CliValidationRules.ExistingDirectory)]
    public string? GamePath { get; set; }

    [CliOption(Required = false, Description = "Path to the columns file generated by export-columns.", ValidationRules = CliValidationRules.ExistingFile)]
    public string? ColumnsFile { get; set; }

    [CliOption(Required = false, Description = "Path to the output file.")]
    public string? OutputPath { get; set; }

    public Task RunAsync()
    {
        var token = Parent.Init();

        var sheets = ColDefReader.FromInputs(GamePath, ColumnsFile);

        if (OutputPath != null)
        {
            using var f = File.OpenWrite(OutputPath);
            f.SetLength(0);
            using var writer = new StreamWriter(f);
            sheets.WriteTo(writer);
        }
        else
            sheets.WriteTo(Console.Out);

        Log.Info($"Hash: {sheets.HashString}");
        return Task.CompletedTask;
    }
}